datasource:
  url: ${POSTGRESQL_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

#liquibase:
#  change-log: db/changelog/changelog-master.xml
#  contexts: dev
#  default-schema-name: app
#  liquibase-schema-name: service
#  search-path: src/main/resources
