services:
  postgres:
    image: postgres:16
    restart: always
    container_name: PersonalFinancialTracker-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tomcat:
    image: tomcat:latest
    container_name: PersonalFinancialTracker-tomcat
    restart: always
    env_file:
      - .env
    environment:
      CATALINA_OPTS: "-DDB_URL=jdbc:postgresql://postgres:5432/${DB_NAME} -DDB_USER=${DB_USERNAME} -DDB_PASSWORD=${DB_PASSWORD}"
    volumes:
      - ./build/libs/PersonalFinancialTracker.war:/usr/local/tomcat/webapps/PersonalFinancialTracker.war
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: