services:
  postgres:
    image: postgres
    restart: always
    container_name: PersonalFinancialTracker-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres-data: